### ISSUE TITLE
Erase bootloader?

### ISSUE THREAD

**Issue by stinkteeth** [Raxone/amlogic-usbdl_s905x2#1]
The instructions state "If not work need erase bootloader".

But the script "dump_erase_bootloader.sh" does not erase the bootloader.

It does back up the bootloader, but then it erases the boot partition, which is different than the bootloader.

Typically it is very destructive to erase the bootloader, while erasing the boot partition is not nearly as destructive.

The instructions should not imply that the script is erasing the bootloader, or else some user might try to manually erase the bootloader, which would not be a good idea.

It also might be a better idea for the script to backup the boot partition, instead of (or, in addition to) the bootloader, since the boot partition is what the script later erases. Or else the user might have an erased boot partition but no backup of that partition.

**Comment by Raxone** [comment]
Fixed problem no need to erase anything to dump bootrom.
