### ISSUE TITLE
No communication with device after erasing bootloader

### ISSUE THREAD

**Issue by Niktendo** [Raxone/amlogic-usbdl_s905x2#2]
Hi there,
I have a Telekom MagentaTV Stick (OTT-G1) device, GX-CHIP with the Amlogic S905Y2.
At first I've tried booting an payload via amlogic-usbdl which gave me an `Segmentation fault (core dumped)` error. - Edit: My fault
Then I run the dump_erase_bootloader shell script which worked perfectly for me, giving me the bootloader.bin dump.
Amlogic-usbdl suddenly returns that my device is password protected.
Now I want to reflash the boot/bootloader partition, but the update-tool which has worked perfectly before it only returns `"error_msg=error` sending control message: Connection timed out"` now.

Now my questions are
1) Which partition has been erased? The script first does a full dump of the bootloader while erasing the boot partition afterwards.
2) Is there a chance to reflash the erased partition to restore the device?

Edit: Sorry I was stupid, fixed the C++ error by reinstalling libusb and giving permissions to amlogic-usbdl.

**Comment by Raxone** [comment]
Ok. 
Do you fix problem or not?
Amlogic usb password protect is burn in efuse and not posibble to skip that what i know.
If you uart/ttl access to the device  you can dump bootloader log there you can see what is problem.
